# ----CAMERA---- #

# 摄像头数量（最多4个）
camera_num: 4

# 摄像头用户名
camera_username_1: admin
camera_username_2: admin
camera_username_3: admin
camera_username_4: admin
# 摄像头密码
camera_password_1: a12345678
camera_password_2: a12345678
camera_password_3: a12345678
camera_password_4: a12345678
# 摄像头IP
camera_ip_1: 192.168.10.17
camera_ip_2: 192.168.10.18
camera_ip_3: 192.168.10.19
camera_ip_4: 192.168.10.20
# 摄像头流地址
camera_stream_1: '/Streaming/Channels/101'
camera_stream_2: '/Streaming/Channels/101'
camera_stream_3: '/Streaming/Channels/101'
camera_stream_4: '/Streaming/Channels/101'

# 摄像头端口(默认554)
camera_port: 554
# 检测休眠间隔（秒）
sleep_time: 0

# ----YOLO---- #

# Pytorch权重文件路径
pth_pt: "pt/best.pt"
# ONNX权重文件路径
pth_onnx: "pt/best.onnx"
# 使用哪一个进行推理("pt" or "onnx")
pt_kd: "onnx"

# ----MYSQL---- #

mysql_username: root
mysql_password: 123456
mysql_ip: 127.0.0.1
mysql_database: test_rdp
mysql_table: rdp_result
# 是否保存所有检测结果("True" or "False")
save_all: 'False'

# ----API---- #
# 修改为本机IP
api_ip: 192.168.1.39
api_port: 5010
mode: 'run'
# 日志文件保存路径
log_path: 'app.log'